### ISSUE TITLE
Getting a "Not a conda environment: new_env/bin/activate"

### ISSUE THREAD

**Issue by ocefpaf** [conda/conda-pack#19]
I tried to export the following env with `conda-pack`:

```yaml
name: GIS
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge/label/dev::rasterio
  - fiona
  - shapely
  - pip:
    - conda-pack
```

I executed the following commands to accomplish this:

```shell
conda env create --name GIS environment.yml
conda activate GIS
conda-pack
conda deactivate
mkdir new_env
tar -xf GIS.tar.gz -C new_env
source activate new_env/bin/activate
```

but I'm getting,

```shell
Not a conda environment: ~/computer_one/new_env/bin/activate
```

Am I doing something wrong here?

I know that that the env is not very conventional, this is part of a demonstration about the power of conda environments where we want to show how to get a dev package, get packages from multiple channels, packages from `pip`, and re-distribute the env with `conda-pack`.
